# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_bd/fft_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_bd || ORIG_REF_NAME==fft_bd} -quiet] -quiet

# IP: bd/fft_bd/ip/fft_bd_xfft_0_0/fft_bd_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_bd_xfft_0_0 || ORIG_REF_NAME==fft_bd_xfft_0_0} -quiet] -quiet

# IP: bd/fft_bd/ip/fft_bd_hls_real2xfft_0_0/fft_bd_hls_real2xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_bd_hls_real2xfft_0_0 || ORIG_REF_NAME==fft_bd_hls_real2xfft_0_0} -quiet] -quiet

# IP: bd/fft_bd/ip/fft_bd_hls_xfft2real_0_0/fft_bd_hls_xfft2real_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_bd_hls_xfft2real_0_0 || ORIG_REF_NAME==fft_bd_hls_xfft2real_0_0} -quiet] -quiet

# IP: bd/fft_bd/ip/fft_bd_xlconstant_0_0/fft_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_bd_xlconstant_0_0 || ORIG_REF_NAME==fft_bd_xlconstant_0_0} -quiet] -quiet

# XDC: bd/fft_bd/fft_bd_ooc.xdc
