-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_xfft2real is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    din_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    din_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    dout_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    din_TVALID : IN STD_LOGIC;
    din_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    dout_V_TVALID : OUT STD_LOGIC;
    dout_V_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of hls_xfft2real is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_xfft2real,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.890000,HLS_SYN_LAT=1037,HLS_SYN_TPT=526,HLS_SYN_MEM=6,HLS_SYN_DSP=4,HLS_SYN_FF=1625,HLS_SYN_LUT=1102,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal descramble_buf_0_M_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_1_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_1_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_1_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_1_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_1_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_1_i_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_1_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_1_t_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_realfft_be_buff_U0_ap_start : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_ap_done : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_ap_continue : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_ap_idle : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_ap_ready : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_realfft_be_buff_U0_din_TREADY : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_descramble_buf_1_M : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_descramble_buf_1_M : STD_LOGIC := '0';
    signal ap_sync_channel_write_descramble_buf_1_M : STD_LOGIC;
    signal ap_channel_done_descramble_buf_0_M : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_descramble_buf_0_M : STD_LOGIC := '0';
    signal ap_sync_channel_write_descramble_buf_0_M : STD_LOGIC;
    signal ap_channel_done_descramble_buf_1_M_1 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_descramble_buf_1_M_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_descramble_buf_1_M_1 : STD_LOGIC;
    signal ap_channel_done_descramble_buf_0_M_1 : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_descramble_buf_0_M_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_descramble_buf_0_M_1 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_ap_start : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_ap_done : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_ap_continue : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_ap_idle : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_ap_ready : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_dout_V_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_realfft_be_desc_U0_dout_V_TVALID : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0 : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1 : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal descramble_buf_0_M_1_i_full_n : STD_LOGIC;
    signal descramble_buf_0_M_1_t_empty_n : STD_LOGIC;
    signal descramble_buf_0_M_1_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_1_t_we1 : STD_LOGIC;
    signal descramble_buf_1_M_1_i_full_n : STD_LOGIC;
    signal descramble_buf_1_M_1_t_empty_n : STD_LOGIC;
    signal descramble_buf_1_M_1_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_1_t_we1 : STD_LOGIC;
    signal descramble_buf_0_M_i_full_n : STD_LOGIC;
    signal descramble_buf_0_M_t_empty_n : STD_LOGIC;
    signal descramble_buf_0_M_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_0_M_t_we1 : STD_LOGIC;
    signal descramble_buf_1_M_i_full_n : STD_LOGIC;
    signal descramble_buf_1_M_t_empty_n : STD_LOGIC;
    signal descramble_buf_1_M_t_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal descramble_buf_1_M_t_we1 : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_start_full_n : STD_LOGIC;
    signal Loop_realfft_be_buff_U0_start_write : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_start_full_n : STD_LOGIC;
    signal Loop_realfft_be_desc_U0_start_write : STD_LOGIC;

    component Loop_realfft_be_buff IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_we0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_we0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        din_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        din_TVALID : IN STD_LOGIC;
        din_TREADY : OUT STD_LOGIC;
        din_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        descramble_buf_0_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_we0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_we0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component Loop_realfft_be_desc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dout_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_V_TVALID : OUT STD_LOGIC;
        dout_V_TREADY : IN STD_LOGIC;
        descramble_buf_0_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_imag_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_imag_V_ce1 : OUT STD_LOGIC;
        descramble_buf_0_M_imag_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_imag_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_imag_V_ce1 : OUT STD_LOGIC;
        descramble_buf_1_M_imag_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_0_M_real_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_0_M_real_V_ce1 : OUT STD_LOGIC;
        descramble_buf_0_M_real_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce0 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        descramble_buf_1_M_real_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        descramble_buf_1_M_real_V_ce1 : OUT STD_LOGIC;
        descramble_buf_1_M_real_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_xfft2real_desg8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        i_ce1 : IN STD_LOGIC;
        i_q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        t_ce1 : IN STD_LOGIC;
        t_q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;



begin
    descramble_buf_0_M_U : component hls_xfft2real_desg8j
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0,
        i_ce0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0,
        i_we0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0,
        i_d0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0,
        i_q0 => descramble_buf_0_M_i_q0,
        i_address1 => ap_const_lv8_0,
        i_ce1 => ap_const_logic_0,
        i_q1 => descramble_buf_0_M_i_q1,
        t_address0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0,
        t_ce0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => descramble_buf_0_M_t_q0,
        t_address1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1,
        t_ce1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1,
        t_q1 => descramble_buf_0_M_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => descramble_buf_0_M_i_full_n,
        i_write => ap_channel_done_descramble_buf_0_M,
        t_empty_n => descramble_buf_0_M_t_empty_n,
        t_read => Loop_realfft_be_desc_U0_ap_ready);

    descramble_buf_1_M_U : component hls_xfft2real_desg8j
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0,
        i_ce0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0,
        i_we0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0,
        i_d0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0,
        i_q0 => descramble_buf_1_M_i_q0,
        i_address1 => ap_const_lv8_0,
        i_ce1 => ap_const_logic_0,
        i_q1 => descramble_buf_1_M_i_q1,
        t_address0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0,
        t_ce0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => descramble_buf_1_M_t_q0,
        t_address1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1,
        t_ce1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1,
        t_q1 => descramble_buf_1_M_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => descramble_buf_1_M_i_full_n,
        i_write => ap_channel_done_descramble_buf_1_M,
        t_empty_n => descramble_buf_1_M_t_empty_n,
        t_read => Loop_realfft_be_desc_U0_ap_ready);

    descramble_buf_0_M_1_U : component hls_xfft2real_desg8j
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0,
        i_ce0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0,
        i_we0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0,
        i_d0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0,
        i_q0 => descramble_buf_0_M_1_i_q0,
        i_address1 => ap_const_lv8_0,
        i_ce1 => ap_const_logic_0,
        i_q1 => descramble_buf_0_M_1_i_q1,
        t_address0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0,
        t_ce0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => descramble_buf_0_M_1_t_q0,
        t_address1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1,
        t_ce1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1,
        t_q1 => descramble_buf_0_M_1_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => descramble_buf_0_M_1_i_full_n,
        i_write => ap_channel_done_descramble_buf_0_M_1,
        t_empty_n => descramble_buf_0_M_1_t_empty_n,
        t_read => Loop_realfft_be_desc_U0_ap_ready);

    descramble_buf_1_M_1_U : component hls_xfft2real_desg8j
    generic map (
        DataWidth => 16,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0,
        i_ce0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0,
        i_we0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0,
        i_d0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0,
        i_q0 => descramble_buf_1_M_1_i_q0,
        i_address1 => ap_const_lv8_0,
        i_ce1 => ap_const_logic_0,
        i_q1 => descramble_buf_1_M_1_i_q1,
        t_address0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0,
        t_ce0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => descramble_buf_1_M_1_t_q0,
        t_address1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1,
        t_ce1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1,
        t_q1 => descramble_buf_1_M_1_t_q1,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => descramble_buf_1_M_1_i_full_n,
        i_write => ap_channel_done_descramble_buf_1_M_1,
        t_empty_n => descramble_buf_1_M_1_t_empty_n,
        t_read => Loop_realfft_be_desc_U0_ap_ready);

    Loop_realfft_be_buff_U0 : component Loop_realfft_be_buff
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_realfft_be_buff_U0_ap_start,
        ap_done => Loop_realfft_be_buff_U0_ap_done,
        ap_continue => Loop_realfft_be_buff_U0_ap_continue,
        ap_idle => Loop_realfft_be_buff_U0_ap_idle,
        ap_ready => Loop_realfft_be_buff_U0_ap_ready,
        descramble_buf_0_M_imag_V_address0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_we0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_we0,
        descramble_buf_0_M_imag_V_d0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_d0,
        descramble_buf_1_M_imag_V_address0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_we0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_we0,
        descramble_buf_1_M_imag_V_d0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_d0,
        din_TDATA => din_TDATA,
        din_TVALID => din_TVALID,
        din_TREADY => Loop_realfft_be_buff_U0_din_TREADY,
        din_TLAST => din_TLAST,
        descramble_buf_0_M_real_V_address0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_we0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_we0,
        descramble_buf_0_M_real_V_d0 => Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_d0,
        descramble_buf_1_M_real_V_address0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_we0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_we0,
        descramble_buf_1_M_real_V_d0 => Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_d0);

    Loop_realfft_be_desc_U0 : component Loop_realfft_be_desc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_realfft_be_desc_U0_ap_start,
        ap_done => Loop_realfft_be_desc_U0_ap_done,
        ap_continue => Loop_realfft_be_desc_U0_ap_continue,
        ap_idle => Loop_realfft_be_desc_U0_ap_idle,
        ap_ready => Loop_realfft_be_desc_U0_ap_ready,
        dout_V_TDATA => Loop_realfft_be_desc_U0_dout_V_TDATA,
        dout_V_TVALID => Loop_realfft_be_desc_U0_dout_V_TVALID,
        dout_V_TREADY => dout_V_TREADY,
        descramble_buf_0_M_imag_V_address0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address0,
        descramble_buf_0_M_imag_V_ce0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce0,
        descramble_buf_0_M_imag_V_q0 => descramble_buf_0_M_1_t_q0,
        descramble_buf_0_M_imag_V_address1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_address1,
        descramble_buf_0_M_imag_V_ce1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_imag_V_ce1,
        descramble_buf_0_M_imag_V_q1 => descramble_buf_0_M_1_t_q1,
        descramble_buf_1_M_imag_V_address0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address0,
        descramble_buf_1_M_imag_V_ce0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce0,
        descramble_buf_1_M_imag_V_q0 => descramble_buf_1_M_1_t_q0,
        descramble_buf_1_M_imag_V_address1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_address1,
        descramble_buf_1_M_imag_V_ce1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_imag_V_ce1,
        descramble_buf_1_M_imag_V_q1 => descramble_buf_1_M_1_t_q1,
        descramble_buf_0_M_real_V_address0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address0,
        descramble_buf_0_M_real_V_ce0 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce0,
        descramble_buf_0_M_real_V_q0 => descramble_buf_0_M_t_q0,
        descramble_buf_0_M_real_V_address1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_address1,
        descramble_buf_0_M_real_V_ce1 => Loop_realfft_be_desc_U0_descramble_buf_0_M_real_V_ce1,
        descramble_buf_0_M_real_V_q1 => descramble_buf_0_M_t_q1,
        descramble_buf_1_M_real_V_address0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address0,
        descramble_buf_1_M_real_V_ce0 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce0,
        descramble_buf_1_M_real_V_q0 => descramble_buf_1_M_t_q0,
        descramble_buf_1_M_real_V_address1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_address1,
        descramble_buf_1_M_real_V_ce1 => Loop_realfft_be_desc_U0_descramble_buf_1_M_real_V_ce1,
        descramble_buf_1_M_real_V_q1 => descramble_buf_1_M_t_q1);





    ap_sync_reg_channel_write_descramble_buf_0_M_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_descramble_buf_0_M <= ap_const_logic_0;
            else
                if (((Loop_realfft_be_buff_U0_ap_done and Loop_realfft_be_buff_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_descramble_buf_0_M <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_descramble_buf_0_M <= ap_sync_channel_write_descramble_buf_0_M;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_descramble_buf_0_M_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_descramble_buf_0_M_1 <= ap_const_logic_0;
            else
                if (((Loop_realfft_be_buff_U0_ap_done and Loop_realfft_be_buff_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_descramble_buf_0_M_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_descramble_buf_0_M_1 <= ap_sync_channel_write_descramble_buf_0_M_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_descramble_buf_1_M_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_descramble_buf_1_M <= ap_const_logic_0;
            else
                if (((Loop_realfft_be_buff_U0_ap_done and Loop_realfft_be_buff_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_descramble_buf_1_M <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_descramble_buf_1_M <= ap_sync_channel_write_descramble_buf_1_M;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_descramble_buf_1_M_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_descramble_buf_1_M_1 <= ap_const_logic_0;
            else
                if (((Loop_realfft_be_buff_U0_ap_done and Loop_realfft_be_buff_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_descramble_buf_1_M_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_descramble_buf_1_M_1 <= ap_sync_channel_write_descramble_buf_1_M_1;
                end if; 
            end if;
        end if;
    end process;

    Loop_realfft_be_buff_U0_ap_continue <= (ap_sync_channel_write_descramble_buf_1_M_1 and ap_sync_channel_write_descramble_buf_1_M and ap_sync_channel_write_descramble_buf_0_M_1 and ap_sync_channel_write_descramble_buf_0_M);
    Loop_realfft_be_buff_U0_ap_start <= ap_start;
    Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n <= descramble_buf_0_M_1_i_full_n;
    Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n <= descramble_buf_0_M_i_full_n;
    Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n <= descramble_buf_1_M_1_i_full_n;
    Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n <= descramble_buf_1_M_i_full_n;
    Loop_realfft_be_buff_U0_start_full_n <= ap_const_logic_1;
    Loop_realfft_be_buff_U0_start_write <= ap_const_logic_0;
    Loop_realfft_be_desc_U0_ap_continue <= ap_const_logic_1;
    Loop_realfft_be_desc_U0_ap_start <= (descramble_buf_1_M_t_empty_n and descramble_buf_1_M_1_t_empty_n and descramble_buf_0_M_t_empty_n and descramble_buf_0_M_1_t_empty_n);
    Loop_realfft_be_desc_U0_start_full_n <= ap_const_logic_1;
    Loop_realfft_be_desc_U0_start_write <= ap_const_logic_0;
    ap_channel_done_descramble_buf_0_M <= ((ap_sync_reg_channel_write_descramble_buf_0_M xor ap_const_logic_1) and Loop_realfft_be_buff_U0_ap_done);
    ap_channel_done_descramble_buf_0_M_1 <= ((ap_sync_reg_channel_write_descramble_buf_0_M_1 xor ap_const_logic_1) and Loop_realfft_be_buff_U0_ap_done);
    ap_channel_done_descramble_buf_1_M <= ((ap_sync_reg_channel_write_descramble_buf_1_M xor ap_const_logic_1) and Loop_realfft_be_buff_U0_ap_done);
    ap_channel_done_descramble_buf_1_M_1 <= ((ap_sync_reg_channel_write_descramble_buf_1_M_1 xor ap_const_logic_1) and Loop_realfft_be_buff_U0_ap_done);
    ap_done <= Loop_realfft_be_desc_U0_ap_done;
    ap_idle <= ((descramble_buf_1_M_t_empty_n xor ap_const_logic_1) and (descramble_buf_0_M_t_empty_n xor ap_const_logic_1) and (descramble_buf_1_M_1_t_empty_n xor ap_const_logic_1) and (descramble_buf_0_M_1_t_empty_n xor ap_const_logic_1) and Loop_realfft_be_desc_U0_ap_idle and Loop_realfft_be_buff_U0_ap_idle);
    ap_ready <= Loop_realfft_be_buff_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_channel_write_descramble_buf_0_M <= ((ap_channel_done_descramble_buf_0_M and Loop_realfft_be_buff_U0_descramble_buf_0_M_real_V_full_n) or ap_sync_reg_channel_write_descramble_buf_0_M);
    ap_sync_channel_write_descramble_buf_0_M_1 <= ((ap_channel_done_descramble_buf_0_M_1 and Loop_realfft_be_buff_U0_descramble_buf_0_M_imag_V_full_n) or ap_sync_reg_channel_write_descramble_buf_0_M_1);
    ap_sync_channel_write_descramble_buf_1_M <= ((ap_channel_done_descramble_buf_1_M and Loop_realfft_be_buff_U0_descramble_buf_1_M_real_V_full_n) or ap_sync_reg_channel_write_descramble_buf_1_M);
    ap_sync_channel_write_descramble_buf_1_M_1 <= ((ap_channel_done_descramble_buf_1_M_1 and Loop_realfft_be_buff_U0_descramble_buf_1_M_imag_V_full_n) or ap_sync_reg_channel_write_descramble_buf_1_M_1);
    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= Loop_realfft_be_desc_U0_ap_done;
    ap_sync_ready <= Loop_realfft_be_buff_U0_ap_ready;
    descramble_buf_0_M_1_t_d1 <= ap_const_lv16_0;
    descramble_buf_0_M_1_t_we1 <= ap_const_logic_0;
    descramble_buf_0_M_t_d1 <= ap_const_lv16_0;
    descramble_buf_0_M_t_we1 <= ap_const_logic_0;
    descramble_buf_1_M_1_t_d1 <= ap_const_lv16_0;
    descramble_buf_1_M_1_t_we1 <= ap_const_logic_0;
    descramble_buf_1_M_t_d1 <= ap_const_lv16_0;
    descramble_buf_1_M_t_we1 <= ap_const_logic_0;
    din_TREADY <= Loop_realfft_be_buff_U0_din_TREADY;
    dout_V_TDATA <= Loop_realfft_be_desc_U0_dout_V_TDATA;
    dout_V_TVALID <= Loop_realfft_be_desc_U0_dout_V_TVALID;
end behav;
