# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/FPGA/project/triad_finder/tom/Vivado/wav_fft/wav_fft.srcs/sources_1/bd/fft_bd/ip/fft_bd_hls_real2xfft_0_0/fft_bd_hls_real2xfft_0_0.xci
# IP: The module: 'fft_bd_hls_real2xfft_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/FPGA/project/triad_finder/tom/Vivado/wav_fft/wav_fft.srcs/sources_1/bd/fft_bd/ip/fft_bd_hls_real2xfft_0_0/constraints/hls_real2xfft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_bd_hls_real2xfft_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: z:/FPGA/project/triad_finder/tom/Vivado/wav_fft/wav_fft.srcs/sources_1/bd/fft_bd/ip/fft_bd_hls_real2xfft_0_0/fft_bd_hls_real2xfft_0_0.xci
# IP: The module: 'fft_bd_hls_real2xfft_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/FPGA/project/triad_finder/tom/Vivado/wav_fft/wav_fft.srcs/sources_1/bd/fft_bd/ip/fft_bd_hls_real2xfft_0_0/constraints/hls_real2xfft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_bd_hls_real2xfft_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
