// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_realfft_be_desc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_realfft_be_desc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_realfft_be_desc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_realfft_be_desc::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_realfft_be_desc::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> Loop_realfft_be_desc::ap_ST_fsm_state15 = "100";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_realfft_be_desc::ap_const_boolean_1 = true;
const bool Loop_realfft_be_desc::ap_const_boolean_0 = false;
const sc_lv<1> Loop_realfft_be_desc::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_realfft_be_desc::ap_const_lv1_1 = "1";
const sc_lv<10> Loop_realfft_be_desc::ap_const_lv10_0 = "0000000000";
const sc_lv<10> Loop_realfft_be_desc::ap_const_lv10_200 = "1000000000";
const sc_lv<10> Loop_realfft_be_desc::ap_const_lv10_1 = "1";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_8 = "1000";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_9 = "1001";
const sc_lv<2> Loop_realfft_be_desc::ap_const_lv2_0 = "00";
const sc_lv<16> Loop_realfft_be_desc::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_10 = "10000";
const sc_lv<17> Loop_realfft_be_desc::ap_const_lv17_0 = "00000000000000000";
const sc_lv<18> Loop_realfft_be_desc::ap_const_lv18_0 = "000000000000000000";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_F = "1111";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_1E = "11110";
const sc_lv<32> Loop_realfft_be_desc::ap_const_lv32_2 = "10";

Loop_realfft_be_desc::Loop_realfft_be_desc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    twid_rom_0_U = new Loop_realfft_be_dbkb("twid_rom_0_U");
    twid_rom_0_U->clk(ap_clk);
    twid_rom_0_U->reset(ap_rst);
    twid_rom_0_U->address0(twid_rom_0_address0);
    twid_rom_0_U->ce0(twid_rom_0_ce0);
    twid_rom_0_U->q0(twid_rom_0_q0);
    twid_rom_1_U = new Loop_realfft_be_dcud("twid_rom_1_U");
    twid_rom_1_U->clk(ap_clk);
    twid_rom_1_U->reset(ap_rst);
    twid_rom_1_U->address0(twid_rom_1_address0);
    twid_rom_1_U->ce0(twid_rom_1_ce0);
    twid_rom_1_U->q0(twid_rom_1_q0);
    hls_xfft2real_muldEe_U8 = new hls_xfft2real_muldEe<1,3,16,16,31>("hls_xfft2real_muldEe_U8");
    hls_xfft2real_muldEe_U8->clk(ap_clk);
    hls_xfft2real_muldEe_U8->reset(ap_rst);
    hls_xfft2real_muldEe_U8->din0(p_Val2_14_reg_850);
    hls_xfft2real_muldEe_U8->din1(grp_fu_634_p1);
    hls_xfft2real_muldEe_U8->ce(grp_fu_634_ce);
    hls_xfft2real_muldEe_U8->dout(grp_fu_634_p2);
    hls_xfft2real_muldEe_U9 = new hls_xfft2real_muldEe<1,3,16,16,31>("hls_xfft2real_muldEe_U9");
    hls_xfft2real_muldEe_U9->clk(ap_clk);
    hls_xfft2real_muldEe_U9->reset(ap_rst);
    hls_xfft2real_muldEe_U9->din0(grp_fu_640_p0);
    hls_xfft2real_muldEe_U9->din1(p_Val2_15_reg_855);
    hls_xfft2real_muldEe_U9->ce(grp_fu_640_ce);
    hls_xfft2real_muldEe_U9->dout(grp_fu_640_p2);
    hls_xfft2real_maceOg_U10 = new hls_xfft2real_maceOg<1,3,16,16,31,31>("hls_xfft2real_maceOg_U10");
    hls_xfft2real_maceOg_U10->clk(ap_clk);
    hls_xfft2real_maceOg_U10->reset(ap_rst);
    hls_xfft2real_maceOg_U10->din0(grp_fu_646_p0);
    hls_xfft2real_maceOg_U10->din1(grp_fu_646_p1);
    hls_xfft2real_maceOg_U10->din2(mul_ln700_reg_899);
    hls_xfft2real_maceOg_U10->ce(grp_fu_646_ce);
    hls_xfft2real_maceOg_U10->dout(grp_fu_646_p3);
    hls_xfft2real_macfYi_U11 = new hls_xfft2real_macfYi<1,3,16,16,31,31>("hls_xfft2real_macfYi_U11");
    hls_xfft2real_macfYi_U11->clk(ap_clk);
    hls_xfft2real_macfYi_U11->reset(ap_rst);
    hls_xfft2real_macfYi_U11->din0(grp_fu_652_p0);
    hls_xfft2real_macfYi_U11->din1(grp_fu_652_p1);
    hls_xfft2real_macfYi_U11->din2(mul_ln1192_reg_904);
    hls_xfft2real_macfYi_U11->ce(grp_fu_652_ce);
    hls_xfft2real_macfYi_U11->dout(grp_fu_652_p3);
    regslice_both_dout_V_U = new regslice_both<32>("regslice_both_dout_V_U");
    regslice_both_dout_V_U->ap_clk(ap_clk);
    regslice_both_dout_V_U->ap_rst(ap_rst);
    regslice_both_dout_V_U->data_in(dout_V_TDATA_int);
    regslice_both_dout_V_U->vld_in(dout_V_TVALID_int);
    regslice_both_dout_V_U->ack_in(dout_V_TREADY_int);
    regslice_both_dout_V_U->data_out(dout_V_TDATA);
    regslice_both_dout_V_U->vld_out(regslice_both_dout_V_U_vld_out);
    regslice_both_dout_V_U->ack_out(dout_V_TREADY);
    regslice_both_dout_V_U->apdone_blk(regslice_both_dout_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_1_fu_619_p2);
    sensitive << ( f_M_imag_V_fu_588_p3 );
    sensitive << ( p_Val2_13_fu_604_p4 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_block_state13_io );
    sensitive << ( ap_block_state14_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_block_state13_io );
    sensitive << ( ap_block_state14_io );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_io);
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( dout_V_TREADY_int );

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_io);
    sensitive << ( icmp_ln80_reg_658_pp0_iter11_reg );
    sensitive << ( dout_V_TREADY_int );

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln80_fu_247_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( regslice_both_dout_V_U_apdone_blk );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4);
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( icmp_ln101_reg_667_pp0_iter10_reg );
    sensitive << ( add_ln703_1_reg_944 );
    sensitive << ( ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238 );

    SC_METHOD(thread_ap_phi_mux_i1_0_i_phi_fu_221_p4);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_658 );
    sensitive << ( i1_0_i_reg_217 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_reg_662 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_tmp_M_real_V_phi_fu_232_p4);
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( icmp_ln101_reg_667_pp0_iter10_reg );
    sensitive << ( cdata_M_real_V_1_reg_939 );
    sensitive << ( ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( regslice_both_dout_V_U_apdone_blk );

    SC_METHOD(thread_cdata_M_real_V_1_fu_613_p2);
    sensitive << ( f_M_real_V_fu_565_p3 );
    sensitive << ( p_r_V_fu_595_p4 );

    SC_METHOD(thread_cdata_M_real_V_fu_541_p2);
    sensitive << ( p_Val2_s_reg_779_pp0_iter8_reg );
    sensitive << ( p_Val2_1_reg_785_pp0_iter8_reg );

    SC_METHOD(thread_descramble_buf_0_M_imag_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln104_fu_283_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_descramble_buf_0_M_imag_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln99_fu_292_p1 );

    SC_METHOD(thread_descramble_buf_0_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_descramble_buf_0_M_imag_V_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_0_M_real_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln99_fu_292_p1 );

    SC_METHOD(thread_descramble_buf_0_M_real_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln104_reg_682 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_0_M_real_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_0_M_real_V_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_1_M_imag_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln104_fu_283_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_descramble_buf_1_M_imag_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln99_fu_292_p1 );

    SC_METHOD(thread_descramble_buf_1_M_imag_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_descramble_buf_1_M_imag_V_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_1_M_real_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln99_fu_292_p1 );

    SC_METHOD(thread_descramble_buf_1_M_real_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln104_reg_682 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_1_M_real_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_descramble_buf_1_M_real_V_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_dout_V_TDATA_blk_n);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( icmp_ln80_reg_658_pp0_iter11_reg );
    sensitive << ( dout_V_TREADY_int );

    SC_METHOD(thread_dout_V_TDATA_int);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( ap_phi_mux_tmp_M_real_V_phi_fu_232_p4 );
    sensitive << ( ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_dout_V_TVALID);
    sensitive << ( regslice_both_dout_V_U_vld_out );

    SC_METHOD(thread_dout_V_TVALID_int);
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( icmp_ln80_reg_658_pp0_iter10_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_f_M_imag_V_fu_588_p3);
    sensitive << ( sub_ln1148_3_reg_914 );
    sensitive << ( tmp_5_fu_572_p3 );
    sensitive << ( trunc_ln1148_5_fu_579_p4 );

    SC_METHOD(thread_f_M_real_V_fu_565_p3);
    sensitive << ( sub_ln1148_1_reg_909 );
    sensitive << ( tmp_4_fu_549_p3 );
    sensitive << ( trunc_ln1148_2_fu_556_p4 );

    SC_METHOD(thread_grp_fu_634_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_634_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_1_fu_484_p1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_METHOD(thread_grp_fu_640_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_640_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_1_fu_484_p1 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_METHOD(thread_grp_fu_646_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_646_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_2_reg_877 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_grp_fu_646_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_3_fu_490_p1 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_grp_fu_652_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_652_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_reg_865 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_grp_fu_652_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_3_fu_490_p1 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_i_fu_253_p2);
    sensitive << ( ap_phi_mux_i1_0_i_phi_fu_221_p4 );

    SC_METHOD(thread_icmp_ln101_fu_259_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_fu_247_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i1_0_i_phi_fu_221_p4 );

    SC_METHOD(thread_icmp_ln80_fu_247_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i1_0_i_phi_fu_221_p4 );

    SC_METHOD(thread_icmp_ln99_fu_310_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_658_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_fu_300_p4 );

    SC_METHOD(thread_lhs_V_4_fu_371_p1);
    sensitive << ( p_Val2_1_fu_338_p3 );

    SC_METHOD(thread_lhs_V_fu_355_p1);
    sensitive << ( p_Val2_s_fu_333_p3 );

    SC_METHOD(thread_p_Val2_13_fu_604_p4);
    sensitive << ( ret_V_5_reg_924 );

    SC_METHOD(thread_p_Val2_1_fu_338_p3);
    sensitive << ( icmp_ln99_reg_738 );
    sensitive << ( descramble_buf_0_M_3_reg_754 );
    sensitive << ( descramble_buf_1_M_3_reg_759 );

    SC_METHOD(thread_p_Val2_2_fu_316_p3);
    sensitive << ( tmp_3_reg_676_pp0_iter2_reg );
    sensitive << ( descramble_buf_0_M_7_reg_728 );
    sensitive << ( descramble_buf_1_M_7_reg_733 );

    SC_METHOD(thread_p_Val2_3_fu_343_p3);
    sensitive << ( tmp_3_reg_676_pp0_iter3_reg );
    sensitive << ( descramble_buf_0_M_6_reg_764 );
    sensitive << ( descramble_buf_1_M_6_reg_769 );

    SC_METHOD(thread_p_Val2_4_fu_321_p2);
    sensitive << ( p_Val2_2_fu_316_p3 );

    SC_METHOD(thread_p_Val2_s_fu_333_p3);
    sensitive << ( icmp_ln99_reg_738 );
    sensitive << ( descramble_buf_0_M_1_reg_744 );
    sensitive << ( descramble_buf_1_M_1_reg_749 );

    SC_METHOD(thread_p_r_V_fu_595_p4);
    sensitive << ( ret_V_4_reg_919 );

    SC_METHOD(thread_r_V_fu_418_p2);
    sensitive << ( ret_V_2_reg_810 );

    SC_METHOD(thread_ret_V_1_fu_375_p2);
    sensitive << ( lhs_V_4_fu_371_p1 );
    sensitive << ( rhs_V_3_fu_352_p1 );

    SC_METHOD(thread_ret_V_2_fu_381_p2);
    sensitive << ( lhs_V_4_fu_371_p1 );
    sensitive << ( rhs_V_3_fu_352_p1 );

    SC_METHOD(thread_ret_V_3_fu_365_p2);
    sensitive << ( lhs_V_fu_355_p1 );
    sensitive << ( rhs_V_fu_348_p1 );

    SC_METHOD(thread_ret_V_fu_359_p2);
    sensitive << ( lhs_V_fu_355_p1 );
    sensitive << ( rhs_V_fu_348_p1 );

    SC_METHOD(thread_rhs_V_3_fu_352_p1);
    sensitive << ( p_Val2_4_reg_774 );

    SC_METHOD(thread_rhs_V_fu_348_p1);
    sensitive << ( p_Val2_3_fu_343_p3 );

    SC_METHOD(thread_select_ln1148_2_fu_475_p3);
    sensitive << ( tmp_7_reg_820_pp0_iter5_reg );
    sensitive << ( trunc_ln1148_3_reg_825_pp0_iter5_reg );
    sensitive << ( sub_ln1148_6_fu_470_p2 );

    SC_METHOD(thread_select_ln1148_fu_446_p3);
    sensitive << ( tmp_6_fu_423_p3 );
    sensitive << ( sub_ln1148_4_fu_431_p2 );
    sensitive << ( trunc_ln1148_8_fu_436_p4 );

    SC_METHOD(thread_sext_ln1118_1_fu_484_p1);
    sensitive << ( select_ln1148_reg_840 );

    SC_METHOD(thread_sext_ln1118_2_fu_487_p1);
    sensitive << ( p_Val2_15_reg_855 );

    SC_METHOD(thread_sext_ln1118_3_fu_490_p1);
    sensitive << ( select_ln1148_2_reg_860 );

    SC_METHOD(thread_sext_ln1118_fu_481_p1);
    sensitive << ( p_Val2_14_reg_850 );

    SC_METHOD(thread_sub_ln104_fu_265_p2);
    sensitive << ( ap_phi_mux_i1_0_i_phi_fu_221_p4 );

    SC_METHOD(thread_sub_ln1148_1_fu_531_p2);
    sensitive << ( trunc_ln1148_1_reg_889 );

    SC_METHOD(thread_sub_ln1148_2_fu_515_p2);
    sensitive << ( zext_ln1148_1_fu_512_p1 );

    SC_METHOD(thread_sub_ln1148_3_fu_536_p2);
    sensitive << ( trunc_ln1148_4_reg_894 );

    SC_METHOD(thread_sub_ln1148_4_fu_431_p2);
    sensitive << ( trunc_ln1148_7_reg_815 );

    SC_METHOD(thread_sub_ln1148_5_fu_454_p2);
    sensitive << ( zext_ln1148_2_fu_415_p1 );

    SC_METHOD(thread_sub_ln1148_6_fu_470_p2);
    sensitive << ( trunc_ln1148_s_reg_845 );

    SC_METHOD(thread_sub_ln1148_fu_496_p2);
    sensitive << ( zext_ln1148_fu_493_p1 );

    SC_METHOD(thread_sub_ln703_fu_545_p2);
    sensitive << ( p_Val2_s_reg_779_pp0_iter8_reg );
    sensitive << ( p_Val2_1_reg_785_pp0_iter8_reg );

    SC_METHOD(thread_tmp_4_fu_549_p3);
    sensitive << ( ret_V_reg_791_pp0_iter9_reg );

    SC_METHOD(thread_tmp_5_fu_572_p3);
    sensitive << ( ret_V_1_reg_803_pp0_iter9_reg );

    SC_METHOD(thread_tmp_6_fu_423_p3);
    sensitive << ( r_V_fu_418_p2 );

    SC_METHOD(thread_tmp_fu_300_p4);
    sensitive << ( i1_0_i_reg_217_pp0_iter2_reg );

    SC_METHOD(thread_trunc_ln104_fu_271_p1);
    sensitive << ( sub_ln104_fu_265_p2 );

    SC_METHOD(thread_trunc_ln1148_2_fu_556_p4);
    sensitive << ( ret_V_reg_791_pp0_iter9_reg );

    SC_METHOD(thread_trunc_ln1148_5_fu_579_p4);
    sensitive << ( ret_V_1_reg_803_pp0_iter9_reg );

    SC_METHOD(thread_trunc_ln1148_8_fu_436_p4);
    sensitive << ( r_V_fu_418_p2 );

    SC_METHOD(thread_trunc_ln99_fu_288_p1);
    sensitive << ( i1_0_i_reg_217_pp0_iter1_reg );

    SC_METHOD(thread_twid_rom_0_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( zext_ln1265_fu_327_p1 );

    SC_METHOD(thread_twid_rom_0_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_twid_rom_1_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( zext_ln1265_fu_327_p1 );

    SC_METHOD(thread_twid_rom_1_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_zext_ln104_fu_283_p1);
    sensitive << ( trunc_ln104_reg_671 );

    SC_METHOD(thread_zext_ln1148_1_fu_512_p1);
    sensitive << ( ret_V_1_reg_803_pp0_iter7_reg );

    SC_METHOD(thread_zext_ln1148_2_fu_415_p1);
    sensitive << ( ret_V_3_reg_798 );

    SC_METHOD(thread_zext_ln1148_fu_493_p1);
    sensitive << ( ret_V_reg_791_pp0_iter7_reg );

    SC_METHOD(thread_zext_ln1265_fu_327_p1);
    sensitive << ( i1_0_i_reg_217_pp0_iter3_reg );

    SC_METHOD(thread_zext_ln99_fu_292_p1);
    sensitive << ( trunc_ln99_fu_288_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( icmp_ln80_fu_247_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( regslice_both_dout_V_U_apdone_blk );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_realfft_be_desc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, dout_V_TDATA, "(port)dout_V_TDATA");
    sc_trace(mVcdFile, dout_V_TVALID, "(port)dout_V_TVALID");
    sc_trace(mVcdFile, dout_V_TREADY, "(port)dout_V_TREADY");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_address0, "(port)descramble_buf_0_M_imag_V_address0");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_ce0, "(port)descramble_buf_0_M_imag_V_ce0");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_q0, "(port)descramble_buf_0_M_imag_V_q0");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_address1, "(port)descramble_buf_0_M_imag_V_address1");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_ce1, "(port)descramble_buf_0_M_imag_V_ce1");
    sc_trace(mVcdFile, descramble_buf_0_M_imag_V_q1, "(port)descramble_buf_0_M_imag_V_q1");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_address0, "(port)descramble_buf_1_M_imag_V_address0");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_ce0, "(port)descramble_buf_1_M_imag_V_ce0");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_q0, "(port)descramble_buf_1_M_imag_V_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_address1, "(port)descramble_buf_1_M_imag_V_address1");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_ce1, "(port)descramble_buf_1_M_imag_V_ce1");
    sc_trace(mVcdFile, descramble_buf_1_M_imag_V_q1, "(port)descramble_buf_1_M_imag_V_q1");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_address0, "(port)descramble_buf_0_M_real_V_address0");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_ce0, "(port)descramble_buf_0_M_real_V_ce0");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_q0, "(port)descramble_buf_0_M_real_V_q0");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_address1, "(port)descramble_buf_0_M_real_V_address1");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_ce1, "(port)descramble_buf_0_M_real_V_ce1");
    sc_trace(mVcdFile, descramble_buf_0_M_real_V_q1, "(port)descramble_buf_0_M_real_V_q1");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_address0, "(port)descramble_buf_1_M_real_V_address0");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_ce0, "(port)descramble_buf_1_M_real_V_ce0");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_q0, "(port)descramble_buf_1_M_real_V_q0");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_address1, "(port)descramble_buf_1_M_real_V_address1");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_ce1, "(port)descramble_buf_1_M_real_V_ce1");
    sc_trace(mVcdFile, descramble_buf_1_M_real_V_q1, "(port)descramble_buf_1_M_real_V_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, twid_rom_0_address0, "twid_rom_0_address0");
    sc_trace(mVcdFile, twid_rom_0_ce0, "twid_rom_0_ce0");
    sc_trace(mVcdFile, twid_rom_0_q0, "twid_rom_0_q0");
    sc_trace(mVcdFile, twid_rom_1_address0, "twid_rom_1_address0");
    sc_trace(mVcdFile, twid_rom_1_ce0, "twid_rom_1_ce0");
    sc_trace(mVcdFile, twid_rom_1_q0, "twid_rom_1_q0");
    sc_trace(mVcdFile, dout_V_TDATA_blk_n, "dout_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln80_reg_658, "icmp_ln80_reg_658");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter10_reg, "icmp_ln80_reg_658_pp0_iter10_reg");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter11_reg, "icmp_ln80_reg_658_pp0_iter11_reg");
    sc_trace(mVcdFile, i1_0_i_reg_217, "i1_0_i_reg_217");
    sc_trace(mVcdFile, i1_0_i_reg_217_pp0_iter1_reg, "i1_0_i_reg_217_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state13_io, "ap_block_state13_io");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state14_io, "ap_block_state14_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i1_0_i_reg_217_pp0_iter2_reg, "i1_0_i_reg_217_pp0_iter2_reg");
    sc_trace(mVcdFile, i1_0_i_reg_217_pp0_iter3_reg, "i1_0_i_reg_217_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln80_fu_247_p2, "icmp_ln80_fu_247_p2");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter1_reg, "icmp_ln80_reg_658_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter2_reg, "icmp_ln80_reg_658_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter3_reg, "icmp_ln80_reg_658_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter4_reg, "icmp_ln80_reg_658_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter5_reg, "icmp_ln80_reg_658_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter6_reg, "icmp_ln80_reg_658_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter7_reg, "icmp_ln80_reg_658_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter8_reg, "icmp_ln80_reg_658_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln80_reg_658_pp0_iter9_reg, "icmp_ln80_reg_658_pp0_iter9_reg");
    sc_trace(mVcdFile, i_fu_253_p2, "i_fu_253_p2");
    sc_trace(mVcdFile, i_reg_662, "i_reg_662");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, icmp_ln101_fu_259_p2, "icmp_ln101_fu_259_p2");
    sc_trace(mVcdFile, icmp_ln101_reg_667, "icmp_ln101_reg_667");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter1_reg, "icmp_ln101_reg_667_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter2_reg, "icmp_ln101_reg_667_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter3_reg, "icmp_ln101_reg_667_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter4_reg, "icmp_ln101_reg_667_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter5_reg, "icmp_ln101_reg_667_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter6_reg, "icmp_ln101_reg_667_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter7_reg, "icmp_ln101_reg_667_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter8_reg, "icmp_ln101_reg_667_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter9_reg, "icmp_ln101_reg_667_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln101_reg_667_pp0_iter10_reg, "icmp_ln101_reg_667_pp0_iter10_reg");
    sc_trace(mVcdFile, trunc_ln104_fu_271_p1, "trunc_ln104_fu_271_p1");
    sc_trace(mVcdFile, trunc_ln104_reg_671, "trunc_ln104_reg_671");
    sc_trace(mVcdFile, tmp_3_reg_676, "tmp_3_reg_676");
    sc_trace(mVcdFile, tmp_3_reg_676_pp0_iter1_reg, "tmp_3_reg_676_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_3_reg_676_pp0_iter2_reg, "tmp_3_reg_676_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_3_reg_676_pp0_iter3_reg, "tmp_3_reg_676_pp0_iter3_reg");
    sc_trace(mVcdFile, zext_ln104_fu_283_p1, "zext_ln104_fu_283_p1");
    sc_trace(mVcdFile, zext_ln104_reg_682, "zext_ln104_reg_682");
    sc_trace(mVcdFile, descramble_buf_0_M_7_reg_728, "descramble_buf_0_M_7_reg_728");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, descramble_buf_1_M_7_reg_733, "descramble_buf_1_M_7_reg_733");
    sc_trace(mVcdFile, icmp_ln99_fu_310_p2, "icmp_ln99_fu_310_p2");
    sc_trace(mVcdFile, icmp_ln99_reg_738, "icmp_ln99_reg_738");
    sc_trace(mVcdFile, descramble_buf_0_M_1_reg_744, "descramble_buf_0_M_1_reg_744");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, descramble_buf_1_M_1_reg_749, "descramble_buf_1_M_1_reg_749");
    sc_trace(mVcdFile, descramble_buf_0_M_3_reg_754, "descramble_buf_0_M_3_reg_754");
    sc_trace(mVcdFile, descramble_buf_1_M_3_reg_759, "descramble_buf_1_M_3_reg_759");
    sc_trace(mVcdFile, descramble_buf_0_M_6_reg_764, "descramble_buf_0_M_6_reg_764");
    sc_trace(mVcdFile, descramble_buf_1_M_6_reg_769, "descramble_buf_1_M_6_reg_769");
    sc_trace(mVcdFile, p_Val2_4_fu_321_p2, "p_Val2_4_fu_321_p2");
    sc_trace(mVcdFile, p_Val2_4_reg_774, "p_Val2_4_reg_774");
    sc_trace(mVcdFile, p_Val2_s_fu_333_p3, "p_Val2_s_fu_333_p3");
    sc_trace(mVcdFile, p_Val2_s_reg_779, "p_Val2_s_reg_779");
    sc_trace(mVcdFile, p_Val2_s_reg_779_pp0_iter5_reg, "p_Val2_s_reg_779_pp0_iter5_reg");
    sc_trace(mVcdFile, p_Val2_s_reg_779_pp0_iter6_reg, "p_Val2_s_reg_779_pp0_iter6_reg");
    sc_trace(mVcdFile, p_Val2_s_reg_779_pp0_iter7_reg, "p_Val2_s_reg_779_pp0_iter7_reg");
    sc_trace(mVcdFile, p_Val2_s_reg_779_pp0_iter8_reg, "p_Val2_s_reg_779_pp0_iter8_reg");
    sc_trace(mVcdFile, p_Val2_1_fu_338_p3, "p_Val2_1_fu_338_p3");
    sc_trace(mVcdFile, p_Val2_1_reg_785, "p_Val2_1_reg_785");
    sc_trace(mVcdFile, p_Val2_1_reg_785_pp0_iter5_reg, "p_Val2_1_reg_785_pp0_iter5_reg");
    sc_trace(mVcdFile, p_Val2_1_reg_785_pp0_iter6_reg, "p_Val2_1_reg_785_pp0_iter6_reg");
    sc_trace(mVcdFile, p_Val2_1_reg_785_pp0_iter7_reg, "p_Val2_1_reg_785_pp0_iter7_reg");
    sc_trace(mVcdFile, p_Val2_1_reg_785_pp0_iter8_reg, "p_Val2_1_reg_785_pp0_iter8_reg");
    sc_trace(mVcdFile, ret_V_fu_359_p2, "ret_V_fu_359_p2");
    sc_trace(mVcdFile, ret_V_reg_791, "ret_V_reg_791");
    sc_trace(mVcdFile, ret_V_reg_791_pp0_iter5_reg, "ret_V_reg_791_pp0_iter5_reg");
    sc_trace(mVcdFile, ret_V_reg_791_pp0_iter6_reg, "ret_V_reg_791_pp0_iter6_reg");
    sc_trace(mVcdFile, ret_V_reg_791_pp0_iter7_reg, "ret_V_reg_791_pp0_iter7_reg");
    sc_trace(mVcdFile, ret_V_reg_791_pp0_iter8_reg, "ret_V_reg_791_pp0_iter8_reg");
    sc_trace(mVcdFile, ret_V_reg_791_pp0_iter9_reg, "ret_V_reg_791_pp0_iter9_reg");
    sc_trace(mVcdFile, ret_V_3_fu_365_p2, "ret_V_3_fu_365_p2");
    sc_trace(mVcdFile, ret_V_3_reg_798, "ret_V_3_reg_798");
    sc_trace(mVcdFile, ret_V_1_fu_375_p2, "ret_V_1_fu_375_p2");
    sc_trace(mVcdFile, ret_V_1_reg_803, "ret_V_1_reg_803");
    sc_trace(mVcdFile, ret_V_1_reg_803_pp0_iter5_reg, "ret_V_1_reg_803_pp0_iter5_reg");
    sc_trace(mVcdFile, ret_V_1_reg_803_pp0_iter6_reg, "ret_V_1_reg_803_pp0_iter6_reg");
    sc_trace(mVcdFile, ret_V_1_reg_803_pp0_iter7_reg, "ret_V_1_reg_803_pp0_iter7_reg");
    sc_trace(mVcdFile, ret_V_1_reg_803_pp0_iter8_reg, "ret_V_1_reg_803_pp0_iter8_reg");
    sc_trace(mVcdFile, ret_V_1_reg_803_pp0_iter9_reg, "ret_V_1_reg_803_pp0_iter9_reg");
    sc_trace(mVcdFile, ret_V_2_fu_381_p2, "ret_V_2_fu_381_p2");
    sc_trace(mVcdFile, ret_V_2_reg_810, "ret_V_2_reg_810");
    sc_trace(mVcdFile, trunc_ln1148_7_reg_815, "trunc_ln1148_7_reg_815");
    sc_trace(mVcdFile, tmp_7_reg_820, "tmp_7_reg_820");
    sc_trace(mVcdFile, tmp_7_reg_820_pp0_iter5_reg, "tmp_7_reg_820_pp0_iter5_reg");
    sc_trace(mVcdFile, trunc_ln1148_3_reg_825, "trunc_ln1148_3_reg_825");
    sc_trace(mVcdFile, trunc_ln1148_3_reg_825_pp0_iter5_reg, "trunc_ln1148_3_reg_825_pp0_iter5_reg");
    sc_trace(mVcdFile, select_ln1148_fu_446_p3, "select_ln1148_fu_446_p3");
    sc_trace(mVcdFile, select_ln1148_reg_840, "select_ln1148_reg_840");
    sc_trace(mVcdFile, trunc_ln1148_s_reg_845, "trunc_ln1148_s_reg_845");
    sc_trace(mVcdFile, p_Val2_14_reg_850, "p_Val2_14_reg_850");
    sc_trace(mVcdFile, p_Val2_15_reg_855, "p_Val2_15_reg_855");
    sc_trace(mVcdFile, select_ln1148_2_fu_475_p3, "select_ln1148_2_fu_475_p3");
    sc_trace(mVcdFile, select_ln1148_2_reg_860, "select_ln1148_2_reg_860");
    sc_trace(mVcdFile, sext_ln1118_fu_481_p1, "sext_ln1118_fu_481_p1");
    sc_trace(mVcdFile, sext_ln1118_reg_865, "sext_ln1118_reg_865");
    sc_trace(mVcdFile, sext_ln1118_1_fu_484_p1, "sext_ln1118_1_fu_484_p1");
    sc_trace(mVcdFile, sext_ln1118_2_fu_487_p1, "sext_ln1118_2_fu_487_p1");
    sc_trace(mVcdFile, sext_ln1118_2_reg_877, "sext_ln1118_2_reg_877");
    sc_trace(mVcdFile, sext_ln1118_3_fu_490_p1, "sext_ln1118_3_fu_490_p1");
    sc_trace(mVcdFile, trunc_ln1148_1_reg_889, "trunc_ln1148_1_reg_889");
    sc_trace(mVcdFile, trunc_ln1148_4_reg_894, "trunc_ln1148_4_reg_894");
    sc_trace(mVcdFile, grp_fu_634_p2, "grp_fu_634_p2");
    sc_trace(mVcdFile, mul_ln700_reg_899, "mul_ln700_reg_899");
    sc_trace(mVcdFile, grp_fu_640_p2, "grp_fu_640_p2");
    sc_trace(mVcdFile, mul_ln1192_reg_904, "mul_ln1192_reg_904");
    sc_trace(mVcdFile, sub_ln1148_1_fu_531_p2, "sub_ln1148_1_fu_531_p2");
    sc_trace(mVcdFile, sub_ln1148_1_reg_909, "sub_ln1148_1_reg_909");
    sc_trace(mVcdFile, sub_ln1148_3_fu_536_p2, "sub_ln1148_3_fu_536_p2");
    sc_trace(mVcdFile, sub_ln1148_3_reg_914, "sub_ln1148_3_reg_914");
    sc_trace(mVcdFile, grp_fu_646_p3, "grp_fu_646_p3");
    sc_trace(mVcdFile, ret_V_4_reg_919, "ret_V_4_reg_919");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, grp_fu_652_p3, "grp_fu_652_p3");
    sc_trace(mVcdFile, ret_V_5_reg_924, "ret_V_5_reg_924");
    sc_trace(mVcdFile, cdata_M_real_V_fu_541_p2, "cdata_M_real_V_fu_541_p2");
    sc_trace(mVcdFile, cdata_M_real_V_reg_929, "cdata_M_real_V_reg_929");
    sc_trace(mVcdFile, sub_ln703_fu_545_p2, "sub_ln703_fu_545_p2");
    sc_trace(mVcdFile, sub_ln703_reg_934, "sub_ln703_reg_934");
    sc_trace(mVcdFile, cdata_M_real_V_1_fu_613_p2, "cdata_M_real_V_1_fu_613_p2");
    sc_trace(mVcdFile, cdata_M_real_V_1_reg_939, "cdata_M_real_V_1_reg_939");
    sc_trace(mVcdFile, add_ln703_1_fu_619_p2, "add_ln703_1_fu_619_p2");
    sc_trace(mVcdFile, add_ln703_1_reg_944, "add_ln703_1_reg_944");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_phi_mux_i1_0_i_phi_fu_221_p4, "ap_phi_mux_i1_0_i_phi_fu_221_p4");
    sc_trace(mVcdFile, ap_phi_mux_tmp_M_real_V_phi_fu_232_p4, "ap_phi_mux_tmp_M_real_V_phi_fu_232_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter1_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter2_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter3_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter4_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter4_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter5_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter5_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter6_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter6_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter7_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter7_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter8_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter8_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter9_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter9_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter10_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter10_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229, "ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229");
    sc_trace(mVcdFile, ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4, "ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter1_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter2_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter3_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter4_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter4_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter5_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter5_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter6_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter6_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter7_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter7_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter8_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter8_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter9_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter9_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter10_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter10_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238, "ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238");
    sc_trace(mVcdFile, zext_ln99_fu_292_p1, "zext_ln99_fu_292_p1");
    sc_trace(mVcdFile, zext_ln1265_fu_327_p1, "zext_ln1265_fu_327_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, sub_ln104_fu_265_p2, "sub_ln104_fu_265_p2");
    sc_trace(mVcdFile, trunc_ln99_fu_288_p1, "trunc_ln99_fu_288_p1");
    sc_trace(mVcdFile, tmp_fu_300_p4, "tmp_fu_300_p4");
    sc_trace(mVcdFile, p_Val2_2_fu_316_p3, "p_Val2_2_fu_316_p3");
    sc_trace(mVcdFile, p_Val2_3_fu_343_p3, "p_Val2_3_fu_343_p3");
    sc_trace(mVcdFile, lhs_V_fu_355_p1, "lhs_V_fu_355_p1");
    sc_trace(mVcdFile, rhs_V_fu_348_p1, "rhs_V_fu_348_p1");
    sc_trace(mVcdFile, lhs_V_4_fu_371_p1, "lhs_V_4_fu_371_p1");
    sc_trace(mVcdFile, rhs_V_3_fu_352_p1, "rhs_V_3_fu_352_p1");
    sc_trace(mVcdFile, r_V_fu_418_p2, "r_V_fu_418_p2");
    sc_trace(mVcdFile, tmp_6_fu_423_p3, "tmp_6_fu_423_p3");
    sc_trace(mVcdFile, sub_ln1148_4_fu_431_p2, "sub_ln1148_4_fu_431_p2");
    sc_trace(mVcdFile, trunc_ln1148_8_fu_436_p4, "trunc_ln1148_8_fu_436_p4");
    sc_trace(mVcdFile, zext_ln1148_2_fu_415_p1, "zext_ln1148_2_fu_415_p1");
    sc_trace(mVcdFile, sub_ln1148_5_fu_454_p2, "sub_ln1148_5_fu_454_p2");
    sc_trace(mVcdFile, sub_ln1148_6_fu_470_p2, "sub_ln1148_6_fu_470_p2");
    sc_trace(mVcdFile, zext_ln1148_fu_493_p1, "zext_ln1148_fu_493_p1");
    sc_trace(mVcdFile, sub_ln1148_fu_496_p2, "sub_ln1148_fu_496_p2");
    sc_trace(mVcdFile, zext_ln1148_1_fu_512_p1, "zext_ln1148_1_fu_512_p1");
    sc_trace(mVcdFile, sub_ln1148_2_fu_515_p2, "sub_ln1148_2_fu_515_p2");
    sc_trace(mVcdFile, tmp_4_fu_549_p3, "tmp_4_fu_549_p3");
    sc_trace(mVcdFile, trunc_ln1148_2_fu_556_p4, "trunc_ln1148_2_fu_556_p4");
    sc_trace(mVcdFile, tmp_5_fu_572_p3, "tmp_5_fu_572_p3");
    sc_trace(mVcdFile, trunc_ln1148_5_fu_579_p4, "trunc_ln1148_5_fu_579_p4");
    sc_trace(mVcdFile, f_M_real_V_fu_565_p3, "f_M_real_V_fu_565_p3");
    sc_trace(mVcdFile, p_r_V_fu_595_p4, "p_r_V_fu_595_p4");
    sc_trace(mVcdFile, f_M_imag_V_fu_588_p3, "f_M_imag_V_fu_588_p3");
    sc_trace(mVcdFile, p_Val2_13_fu_604_p4, "p_Val2_13_fu_604_p4");
    sc_trace(mVcdFile, grp_fu_634_p1, "grp_fu_634_p1");
    sc_trace(mVcdFile, grp_fu_640_p0, "grp_fu_640_p0");
    sc_trace(mVcdFile, grp_fu_646_p0, "grp_fu_646_p0");
    sc_trace(mVcdFile, grp_fu_646_p1, "grp_fu_646_p1");
    sc_trace(mVcdFile, grp_fu_652_p0, "grp_fu_652_p0");
    sc_trace(mVcdFile, grp_fu_652_p1, "grp_fu_652_p1");
    sc_trace(mVcdFile, grp_fu_634_ce, "grp_fu_634_ce");
    sc_trace(mVcdFile, grp_fu_640_ce, "grp_fu_640_ce");
    sc_trace(mVcdFile, grp_fu_646_ce, "grp_fu_646_ce");
    sc_trace(mVcdFile, grp_fu_652_ce, "grp_fu_652_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, regslice_both_dout_V_U_apdone_blk, "regslice_both_dout_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, dout_V_TDATA_int, "dout_V_TDATA_int");
    sc_trace(mVcdFile, dout_V_TVALID_int, "dout_V_TVALID_int");
    sc_trace(mVcdFile, dout_V_TREADY_int, "dout_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_dout_V_U_vld_out, "regslice_both_dout_V_U_vld_out");
#endif

    }
}

Loop_realfft_be_desc::~Loop_realfft_be_desc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete twid_rom_0_U;
    delete twid_rom_1_U;
    delete hls_xfft2real_muldEe_U8;
    delete hls_xfft2real_muldEe_U9;
    delete hls_xfft2real_maceOg_U10;
    delete hls_xfft2real_macfYi_U11;
    delete regslice_both_dout_V_U;
}

void Loop_realfft_be_desc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                    esl_seteq<1,1,1>(regslice_both_dout_V_U_apdone_blk.read(), ap_const_logic_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter12 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()))) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter9_reg.read()) && 
             esl_seteq<1,1,1>(icmp_ln101_reg_667_pp0_iter9_reg.read(), ap_const_lv1_1))) {
            ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238 = sub_ln703_reg_934.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter10_cdata_M_imag_V_reg_238.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()))) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter9_reg.read()) && 
             esl_seteq<1,1,1>(icmp_ln101_reg_667_pp0_iter9_reg.read(), ap_const_lv1_1))) {
            ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229 = cdata_M_real_V_reg_929.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter10_tmp_M_real_V_reg_229.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i1_0_i_reg_217 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(icmp_ln80_reg_658.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i1_0_i_reg_217 = i_reg_662.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter9_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter9_reg.read()))) {
        add_ln703_1_reg_944 = add_ln703_1_fu_619_p2.read();
        cdata_M_real_V_1_reg_939 = cdata_M_real_V_1_fu_613_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        ap_phi_reg_pp0_iter10_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter9_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter10_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter9_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        ap_phi_reg_pp0_iter1_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter1_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229.read();
        i_reg_662 = i_fu_253_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_reg_pp0_iter2_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter1_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter2_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter1_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        ap_phi_reg_pp0_iter3_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter2_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter3_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter2_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_phi_reg_pp0_iter4_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter3_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter4_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter3_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        ap_phi_reg_pp0_iter5_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter4_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter5_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter4_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        ap_phi_reg_pp0_iter6_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter5_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter6_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter5_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()))) {
        ap_phi_reg_pp0_iter7_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter6_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter7_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter6_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()))) {
        ap_phi_reg_pp0_iter8_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter7_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter8_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter7_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()))) {
        ap_phi_reg_pp0_iter9_cdata_M_imag_V_reg_238 = ap_phi_reg_pp0_iter8_cdata_M_imag_V_reg_238.read();
        ap_phi_reg_pp0_iter9_tmp_M_real_V_reg_229 = ap_phi_reg_pp0_iter8_tmp_M_real_V_reg_229.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter8_reg.read()) && esl_seteq<1,1,1>(icmp_ln101_reg_667_pp0_iter8_reg.read(), ap_const_lv1_1))) {
        cdata_M_real_V_reg_929 = cdata_M_real_V_fu_541_p2.read();
        sub_ln703_reg_934 = sub_ln703_fu_545_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        descramble_buf_0_M_1_reg_744 = descramble_buf_0_M_real_V_q0.read();
        descramble_buf_0_M_3_reg_754 = descramble_buf_0_M_imag_V_q1.read();
        descramble_buf_1_M_1_reg_749 = descramble_buf_1_M_real_V_q0.read();
        descramble_buf_1_M_3_reg_759 = descramble_buf_1_M_imag_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_676_pp0_iter2_reg.read()))) {
        descramble_buf_0_M_6_reg_764 = descramble_buf_0_M_real_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_reg_676_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_0_M_7_reg_728 = descramble_buf_0_M_imag_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(tmp_3_reg_676_pp0_iter2_reg.read(), ap_const_lv1_1))) {
        descramble_buf_1_M_6_reg_769 = descramble_buf_1_M_real_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(tmp_3_reg_676_pp0_iter1_reg.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_1_M_7_reg_733 = descramble_buf_1_M_imag_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i1_0_i_reg_217_pp0_iter1_reg = i1_0_i_reg_217.read();
        icmp_ln101_reg_667_pp0_iter1_reg = icmp_ln101_reg_667.read();
        icmp_ln80_reg_658 = icmp_ln80_fu_247_p2.read();
        icmp_ln80_reg_658_pp0_iter1_reg = icmp_ln80_reg_658.read();
        tmp_3_reg_676_pp0_iter1_reg = tmp_3_reg_676.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        i1_0_i_reg_217_pp0_iter2_reg = i1_0_i_reg_217_pp0_iter1_reg.read();
        i1_0_i_reg_217_pp0_iter3_reg = i1_0_i_reg_217_pp0_iter2_reg.read();
        icmp_ln101_reg_667_pp0_iter10_reg = icmp_ln101_reg_667_pp0_iter9_reg.read();
        icmp_ln101_reg_667_pp0_iter2_reg = icmp_ln101_reg_667_pp0_iter1_reg.read();
        icmp_ln101_reg_667_pp0_iter3_reg = icmp_ln101_reg_667_pp0_iter2_reg.read();
        icmp_ln101_reg_667_pp0_iter4_reg = icmp_ln101_reg_667_pp0_iter3_reg.read();
        icmp_ln101_reg_667_pp0_iter5_reg = icmp_ln101_reg_667_pp0_iter4_reg.read();
        icmp_ln101_reg_667_pp0_iter6_reg = icmp_ln101_reg_667_pp0_iter5_reg.read();
        icmp_ln101_reg_667_pp0_iter7_reg = icmp_ln101_reg_667_pp0_iter6_reg.read();
        icmp_ln101_reg_667_pp0_iter8_reg = icmp_ln101_reg_667_pp0_iter7_reg.read();
        icmp_ln101_reg_667_pp0_iter9_reg = icmp_ln101_reg_667_pp0_iter8_reg.read();
        icmp_ln80_reg_658_pp0_iter10_reg = icmp_ln80_reg_658_pp0_iter9_reg.read();
        icmp_ln80_reg_658_pp0_iter11_reg = icmp_ln80_reg_658_pp0_iter10_reg.read();
        icmp_ln80_reg_658_pp0_iter2_reg = icmp_ln80_reg_658_pp0_iter1_reg.read();
        icmp_ln80_reg_658_pp0_iter3_reg = icmp_ln80_reg_658_pp0_iter2_reg.read();
        icmp_ln80_reg_658_pp0_iter4_reg = icmp_ln80_reg_658_pp0_iter3_reg.read();
        icmp_ln80_reg_658_pp0_iter5_reg = icmp_ln80_reg_658_pp0_iter4_reg.read();
        icmp_ln80_reg_658_pp0_iter6_reg = icmp_ln80_reg_658_pp0_iter5_reg.read();
        icmp_ln80_reg_658_pp0_iter7_reg = icmp_ln80_reg_658_pp0_iter6_reg.read();
        icmp_ln80_reg_658_pp0_iter8_reg = icmp_ln80_reg_658_pp0_iter7_reg.read();
        icmp_ln80_reg_658_pp0_iter9_reg = icmp_ln80_reg_658_pp0_iter8_reg.read();
        p_Val2_1_reg_785_pp0_iter5_reg = p_Val2_1_reg_785.read();
        p_Val2_1_reg_785_pp0_iter6_reg = p_Val2_1_reg_785_pp0_iter5_reg.read();
        p_Val2_1_reg_785_pp0_iter7_reg = p_Val2_1_reg_785_pp0_iter6_reg.read();
        p_Val2_1_reg_785_pp0_iter8_reg = p_Val2_1_reg_785_pp0_iter7_reg.read();
        p_Val2_s_reg_779_pp0_iter5_reg = p_Val2_s_reg_779.read();
        p_Val2_s_reg_779_pp0_iter6_reg = p_Val2_s_reg_779_pp0_iter5_reg.read();
        p_Val2_s_reg_779_pp0_iter7_reg = p_Val2_s_reg_779_pp0_iter6_reg.read();
        p_Val2_s_reg_779_pp0_iter8_reg = p_Val2_s_reg_779_pp0_iter7_reg.read();
        ret_V_1_reg_803_pp0_iter5_reg = ret_V_1_reg_803.read();
        ret_V_1_reg_803_pp0_iter6_reg = ret_V_1_reg_803_pp0_iter5_reg.read();
        ret_V_1_reg_803_pp0_iter7_reg = ret_V_1_reg_803_pp0_iter6_reg.read();
        ret_V_1_reg_803_pp0_iter8_reg = ret_V_1_reg_803_pp0_iter7_reg.read();
        ret_V_1_reg_803_pp0_iter9_reg = ret_V_1_reg_803_pp0_iter8_reg.read();
        ret_V_reg_791_pp0_iter5_reg = ret_V_reg_791.read();
        ret_V_reg_791_pp0_iter6_reg = ret_V_reg_791_pp0_iter5_reg.read();
        ret_V_reg_791_pp0_iter7_reg = ret_V_reg_791_pp0_iter6_reg.read();
        ret_V_reg_791_pp0_iter8_reg = ret_V_reg_791_pp0_iter7_reg.read();
        ret_V_reg_791_pp0_iter9_reg = ret_V_reg_791_pp0_iter8_reg.read();
        tmp_3_reg_676_pp0_iter2_reg = tmp_3_reg_676_pp0_iter1_reg.read();
        tmp_3_reg_676_pp0_iter3_reg = tmp_3_reg_676_pp0_iter2_reg.read();
        tmp_7_reg_820_pp0_iter5_reg = tmp_7_reg_820.read();
        trunc_ln1148_3_reg_825_pp0_iter5_reg = trunc_ln1148_3_reg_825.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_247_p2.read()))) {
        icmp_ln101_reg_667 = icmp_ln101_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter2_reg.read()))) {
        icmp_ln99_reg_738 = icmp_ln99_fu_310_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter7_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter7_reg.read()))) {
        mul_ln1192_reg_904 = grp_fu_640_p2.read();
        mul_ln700_reg_899 = grp_fu_634_p2.read();
        trunc_ln1148_1_reg_889 = sub_ln1148_fu_496_p2.read().range(16, 1);
        trunc_ln1148_4_reg_894 = sub_ln1148_2_fu_515_p2.read().range(16, 1);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter4_reg.read()))) {
        p_Val2_14_reg_850 = twid_rom_0_q0.read();
        p_Val2_15_reg_855 = twid_rom_1_q0.read();
        select_ln1148_reg_840 = select_ln1148_fu_446_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter3_reg.read()))) {
        p_Val2_1_reg_785 = p_Val2_1_fu_338_p3.read();
        p_Val2_s_reg_779 = p_Val2_s_fu_333_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter2_reg.read()))) {
        p_Val2_4_reg_774 = p_Val2_4_fu_321_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter3_reg.read()))) {
        ret_V_1_reg_803 = ret_V_1_fu_375_p2.read();
        ret_V_2_reg_810 = ret_V_2_fu_381_p2.read();
        ret_V_3_reg_798 = ret_V_3_fu_365_p2.read();
        ret_V_reg_791 = ret_V_fu_359_p2.read();
        tmp_7_reg_820 = ret_V_3_fu_365_p2.read().range(16, 16);
        trunc_ln1148_3_reg_825 = ret_V_3_fu_365_p2.read().range(16, 1);
        trunc_ln1148_7_reg_815 = ret_V_2_fu_381_p2.read().range(16, 1);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter8_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter8_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        ret_V_4_reg_919 = grp_fu_646_p3.read();
        ret_V_5_reg_924 = grp_fu_652_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter5_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter5_reg.read()))) {
        select_ln1148_2_reg_860 = select_ln1148_2_fu_475_p3.read();
        sext_ln1118_2_reg_877 = sext_ln1118_2_fu_487_p1.read();
        sext_ln1118_reg_865 = sext_ln1118_fu_481_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter8_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter8_reg.read()))) {
        sub_ln1148_1_reg_909 = sub_ln1148_1_fu_531_p2.read();
        sub_ln1148_3_reg_914 = sub_ln1148_3_fu_536_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_247_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_259_p2.read()))) {
        tmp_3_reg_676 = sub_ln104_fu_265_p2.read().range(8, 8);
        trunc_ln104_reg_671 = trunc_ln104_fu_271_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_7_reg_820.read()))) {
        trunc_ln1148_s_reg_845 = sub_ln1148_5_fu_454_p2.read().range(16, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_658.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667.read()))) {
        zext_ln104_reg_682 = zext_ln104_fu_283_p1.read();
    }
}

void Loop_realfft_be_desc::thread_add_ln703_1_fu_619_p2() {
    add_ln703_1_fu_619_p2 = (!f_M_imag_V_fu_588_p3.read().is_01() || !p_Val2_13_fu_604_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(f_M_imag_V_fu_588_p3.read()) + sc_biguint<16>(p_Val2_13_fu_604_p4.read()));
}

void Loop_realfft_be_desc::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Loop_realfft_be_desc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_realfft_be_desc::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[2];
}

void Loop_realfft_be_desc::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state13_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter12.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state14_io.read())));
}

void Loop_realfft_be_desc::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state13_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter12.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state14_io.read())));
}

void Loop_realfft_be_desc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_realfft_be_desc::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state13_io() {
    ap_block_state13_io = (esl_seteq<1,1,1>(icmp_ln80_reg_658_pp0_iter10_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, dout_V_TREADY_int.read()));
}

void Loop_realfft_be_desc::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state14_io() {
    ap_block_state14_io = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter11_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, dout_V_TREADY_int.read()));
}

void Loop_realfft_be_desc::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_realfft_be_desc::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln80_fu_247_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(regslice_both_dout_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_realfft_be_desc::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_realfft_be_desc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln80_reg_658_pp0_iter10_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter10_reg.read()))) {
        ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4 = add_ln703_1_reg_944.read();
    } else {
        ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4 = ap_phi_reg_pp0_iter11_cdata_M_imag_V_reg_238.read();
    }
}

void Loop_realfft_be_desc::thread_ap_phi_mux_i1_0_i_phi_fu_221_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_658.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_mux_i1_0_i_phi_fu_221_p4 = i_reg_662.read();
    } else {
        ap_phi_mux_i1_0_i_phi_fu_221_p4 = i1_0_i_reg_217.read();
    }
}

void Loop_realfft_be_desc::thread_ap_phi_mux_tmp_M_real_V_phi_fu_232_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln80_reg_658_pp0_iter10_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_reg_667_pp0_iter10_reg.read()))) {
        ap_phi_mux_tmp_M_real_V_phi_fu_232_p4 = cdata_M_real_V_1_reg_939.read();
    } else {
        ap_phi_mux_tmp_M_real_V_phi_fu_232_p4 = ap_phi_reg_pp0_iter11_tmp_M_real_V_reg_229.read();
    }
}

void Loop_realfft_be_desc::thread_ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238() {
    ap_phi_reg_pp0_iter0_cdata_M_imag_V_reg_238 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
}

void Loop_realfft_be_desc::thread_ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229() {
    ap_phi_reg_pp0_iter0_tmp_M_real_V_reg_229 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
}

void Loop_realfft_be_desc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(regslice_both_dout_V_U_apdone_blk.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_cdata_M_real_V_1_fu_613_p2() {
    cdata_M_real_V_1_fu_613_p2 = (!f_M_real_V_fu_565_p3.read().is_01() || !p_r_V_fu_595_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(f_M_real_V_fu_565_p3.read()) + sc_biguint<16>(p_r_V_fu_595_p4.read()));
}

void Loop_realfft_be_desc::thread_cdata_M_real_V_fu_541_p2() {
    cdata_M_real_V_fu_541_p2 = (!p_Val2_1_reg_785_pp0_iter8_reg.read().is_01() || !p_Val2_s_reg_779_pp0_iter8_reg.read().is_01())? sc_lv<16>(): (sc_bigint<16>(p_Val2_1_reg_785_pp0_iter8_reg.read()) + sc_bigint<16>(p_Val2_s_reg_779_pp0_iter8_reg.read()));
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_imag_V_address0() {
    descramble_buf_0_M_imag_V_address0 =  (sc_lv<8>) (zext_ln104_fu_283_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_imag_V_address1() {
    descramble_buf_0_M_imag_V_address1 =  (sc_lv<8>) (zext_ln99_fu_292_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        descramble_buf_0_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        descramble_buf_0_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_imag_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_0_M_imag_V_ce1 = ap_const_logic_1;
    } else {
        descramble_buf_0_M_imag_V_ce1 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_real_V_address0() {
    descramble_buf_0_M_real_V_address0 =  (sc_lv<8>) (zext_ln99_fu_292_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_real_V_address1() {
    descramble_buf_0_M_real_V_address1 =  (sc_lv<8>) (zext_ln104_reg_682.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_0_M_real_V_ce0 = ap_const_logic_1;
    } else {
        descramble_buf_0_M_real_V_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_0_M_real_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_0_M_real_V_ce1 = ap_const_logic_1;
    } else {
        descramble_buf_0_M_real_V_ce1 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_imag_V_address0() {
    descramble_buf_1_M_imag_V_address0 =  (sc_lv<8>) (zext_ln104_fu_283_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_imag_V_address1() {
    descramble_buf_1_M_imag_V_address1 =  (sc_lv<8>) (zext_ln99_fu_292_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_imag_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        descramble_buf_1_M_imag_V_ce0 = ap_const_logic_1;
    } else {
        descramble_buf_1_M_imag_V_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_imag_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_1_M_imag_V_ce1 = ap_const_logic_1;
    } else {
        descramble_buf_1_M_imag_V_ce1 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_real_V_address0() {
    descramble_buf_1_M_real_V_address0 =  (sc_lv<8>) (zext_ln99_fu_292_p1.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_real_V_address1() {
    descramble_buf_1_M_real_V_address1 =  (sc_lv<8>) (zext_ln104_reg_682.read());
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_real_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_1_M_real_V_ce0 = ap_const_logic_1;
    } else {
        descramble_buf_1_M_real_V_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_descramble_buf_1_M_real_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        descramble_buf_1_M_real_V_ce1 = ap_const_logic_1;
    } else {
        descramble_buf_1_M_real_V_ce1 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_dout_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln80_reg_658_pp0_iter10_reg.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter12.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_reg_658_pp0_iter11_reg.read())))) {
        dout_V_TDATA_blk_n = dout_V_TREADY_int.read();
    } else {
        dout_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void Loop_realfft_be_desc::thread_dout_V_TDATA_int() {
    dout_V_TDATA_int = esl_concat<16,16>(ap_phi_mux_cdata_M_imag_V_phi_fu_241_p4.read(), ap_phi_mux_tmp_M_real_V_phi_fu_232_p4.read());
}

void Loop_realfft_be_desc::thread_dout_V_TVALID() {
    dout_V_TVALID = regslice_both_dout_V_U_vld_out.read();
}

void Loop_realfft_be_desc::thread_dout_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_658_pp0_iter10_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        dout_V_TVALID_int = ap_const_logic_1;
    } else {
        dout_V_TVALID_int = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_f_M_imag_V_fu_588_p3() {
    f_M_imag_V_fu_588_p3 = (!tmp_5_fu_572_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_5_fu_572_p3.read()[0].to_bool())? sub_ln1148_3_reg_914.read(): trunc_ln1148_5_fu_579_p4.read());
}

void Loop_realfft_be_desc::thread_f_M_real_V_fu_565_p3() {
    f_M_real_V_fu_565_p3 = (!tmp_4_fu_549_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_4_fu_549_p3.read()[0].to_bool())? sub_ln1148_1_reg_909.read(): trunc_ln1148_2_fu_556_p4.read());
}

void Loop_realfft_be_desc::thread_grp_fu_634_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_634_ce = ap_const_logic_1;
    } else {
        grp_fu_634_ce = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_grp_fu_634_p1() {
    grp_fu_634_p1 =  (sc_lv<16>) (sext_ln1118_1_fu_484_p1.read());
}

void Loop_realfft_be_desc::thread_grp_fu_640_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_640_ce = ap_const_logic_1;
    } else {
        grp_fu_640_ce = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_grp_fu_640_p0() {
    grp_fu_640_p0 =  (sc_lv<16>) (sext_ln1118_1_fu_484_p1.read());
}

void Loop_realfft_be_desc::thread_grp_fu_646_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_646_ce = ap_const_logic_1;
    } else {
        grp_fu_646_ce = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_grp_fu_646_p0() {
    grp_fu_646_p0 =  (sc_lv<16>) (sext_ln1118_2_reg_877.read());
}

void Loop_realfft_be_desc::thread_grp_fu_646_p1() {
    grp_fu_646_p1 =  (sc_lv<16>) (sext_ln1118_3_fu_490_p1.read());
}

void Loop_realfft_be_desc::thread_grp_fu_652_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_652_ce = ap_const_logic_1;
    } else {
        grp_fu_652_ce = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_grp_fu_652_p0() {
    grp_fu_652_p0 =  (sc_lv<16>) (sext_ln1118_reg_865.read());
}

void Loop_realfft_be_desc::thread_grp_fu_652_p1() {
    grp_fu_652_p1 =  (sc_lv<16>) (sext_ln1118_3_fu_490_p1.read());
}

void Loop_realfft_be_desc::thread_i_fu_253_p2() {
    i_fu_253_p2 = (!ap_phi_mux_i1_0_i_phi_fu_221_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(ap_phi_mux_i1_0_i_phi_fu_221_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void Loop_realfft_be_desc::thread_icmp_ln101_fu_259_p2() {
    icmp_ln101_fu_259_p2 = (!ap_phi_mux_i1_0_i_phi_fu_221_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_0_i_phi_fu_221_p4.read() == ap_const_lv10_0);
}

void Loop_realfft_be_desc::thread_icmp_ln80_fu_247_p2() {
    icmp_ln80_fu_247_p2 = (!ap_phi_mux_i1_0_i_phi_fu_221_p4.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i1_0_i_phi_fu_221_p4.read() == ap_const_lv10_200);
}

void Loop_realfft_be_desc::thread_icmp_ln99_fu_310_p2() {
    icmp_ln99_fu_310_p2 = (!tmp_fu_300_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_300_p4.read() == ap_const_lv2_0);
}

void Loop_realfft_be_desc::thread_lhs_V_4_fu_371_p1() {
    lhs_V_4_fu_371_p1 = esl_sext<17,16>(p_Val2_1_fu_338_p3.read());
}

void Loop_realfft_be_desc::thread_lhs_V_fu_355_p1() {
    lhs_V_fu_355_p1 = esl_sext<17,16>(p_Val2_s_fu_333_p3.read());
}

void Loop_realfft_be_desc::thread_p_Val2_13_fu_604_p4() {
    p_Val2_13_fu_604_p4 = ret_V_5_reg_924.read().range(30, 15);
}

void Loop_realfft_be_desc::thread_p_Val2_1_fu_338_p3() {
    p_Val2_1_fu_338_p3 = (!icmp_ln99_reg_738.read()[0].is_01())? sc_lv<16>(): ((icmp_ln99_reg_738.read()[0].to_bool())? descramble_buf_0_M_3_reg_754.read(): descramble_buf_1_M_3_reg_759.read());
}

void Loop_realfft_be_desc::thread_p_Val2_2_fu_316_p3() {
    p_Val2_2_fu_316_p3 = (!tmp_3_reg_676_pp0_iter2_reg.read()[0].is_01())? sc_lv<16>(): ((tmp_3_reg_676_pp0_iter2_reg.read()[0].to_bool())? descramble_buf_1_M_7_reg_733.read(): descramble_buf_0_M_7_reg_728.read());
}

void Loop_realfft_be_desc::thread_p_Val2_3_fu_343_p3() {
    p_Val2_3_fu_343_p3 = (!tmp_3_reg_676_pp0_iter3_reg.read()[0].is_01())? sc_lv<16>(): ((tmp_3_reg_676_pp0_iter3_reg.read()[0].to_bool())? descramble_buf_1_M_6_reg_769.read(): descramble_buf_0_M_6_reg_764.read());
}

void Loop_realfft_be_desc::thread_p_Val2_4_fu_321_p2() {
    p_Val2_4_fu_321_p2 = (!ap_const_lv16_0.is_01() || !p_Val2_2_fu_316_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(p_Val2_2_fu_316_p3.read()));
}

void Loop_realfft_be_desc::thread_p_Val2_s_fu_333_p3() {
    p_Val2_s_fu_333_p3 = (!icmp_ln99_reg_738.read()[0].is_01())? sc_lv<16>(): ((icmp_ln99_reg_738.read()[0].to_bool())? descramble_buf_0_M_1_reg_744.read(): descramble_buf_1_M_1_reg_749.read());
}

void Loop_realfft_be_desc::thread_p_r_V_fu_595_p4() {
    p_r_V_fu_595_p4 = ret_V_4_reg_919.read().range(30, 15);
}

void Loop_realfft_be_desc::thread_r_V_fu_418_p2() {
    r_V_fu_418_p2 = (!ap_const_lv17_0.is_01() || !ret_V_2_reg_810.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(ret_V_2_reg_810.read()));
}

void Loop_realfft_be_desc::thread_ret_V_1_fu_375_p2() {
    ret_V_1_fu_375_p2 = (!lhs_V_4_fu_371_p1.read().is_01() || !rhs_V_3_fu_352_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(lhs_V_4_fu_371_p1.read()) + sc_bigint<17>(rhs_V_3_fu_352_p1.read()));
}

void Loop_realfft_be_desc::thread_ret_V_2_fu_381_p2() {
    ret_V_2_fu_381_p2 = (!rhs_V_3_fu_352_p1.read().is_01() || !lhs_V_4_fu_371_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(rhs_V_3_fu_352_p1.read()) - sc_bigint<17>(lhs_V_4_fu_371_p1.read()));
}

void Loop_realfft_be_desc::thread_ret_V_3_fu_365_p2() {
    ret_V_3_fu_365_p2 = (!rhs_V_fu_348_p1.read().is_01() || !lhs_V_fu_355_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(rhs_V_fu_348_p1.read()) - sc_bigint<17>(lhs_V_fu_355_p1.read()));
}

void Loop_realfft_be_desc::thread_ret_V_fu_359_p2() {
    ret_V_fu_359_p2 = (!lhs_V_fu_355_p1.read().is_01() || !rhs_V_fu_348_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(lhs_V_fu_355_p1.read()) + sc_bigint<17>(rhs_V_fu_348_p1.read()));
}

void Loop_realfft_be_desc::thread_rhs_V_3_fu_352_p1() {
    rhs_V_3_fu_352_p1 = esl_sext<17,16>(p_Val2_4_reg_774.read());
}

void Loop_realfft_be_desc::thread_rhs_V_fu_348_p1() {
    rhs_V_fu_348_p1 = esl_sext<17,16>(p_Val2_3_fu_343_p3.read());
}

void Loop_realfft_be_desc::thread_select_ln1148_2_fu_475_p3() {
    select_ln1148_2_fu_475_p3 = (!tmp_7_reg_820_pp0_iter5_reg.read()[0].is_01())? sc_lv<16>(): ((tmp_7_reg_820_pp0_iter5_reg.read()[0].to_bool())? sub_ln1148_6_fu_470_p2.read(): trunc_ln1148_3_reg_825_pp0_iter5_reg.read());
}

void Loop_realfft_be_desc::thread_select_ln1148_fu_446_p3() {
    select_ln1148_fu_446_p3 = (!tmp_6_fu_423_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_6_fu_423_p3.read()[0].to_bool())? sub_ln1148_4_fu_431_p2.read(): trunc_ln1148_8_fu_436_p4.read());
}

void Loop_realfft_be_desc::thread_sext_ln1118_1_fu_484_p1() {
    sext_ln1118_1_fu_484_p1 = esl_sext<31,16>(select_ln1148_reg_840.read());
}

void Loop_realfft_be_desc::thread_sext_ln1118_2_fu_487_p1() {
    sext_ln1118_2_fu_487_p1 = esl_sext<31,16>(p_Val2_15_reg_855.read());
}

void Loop_realfft_be_desc::thread_sext_ln1118_3_fu_490_p1() {
    sext_ln1118_3_fu_490_p1 = esl_sext<31,16>(select_ln1148_2_reg_860.read());
}

void Loop_realfft_be_desc::thread_sext_ln1118_fu_481_p1() {
    sext_ln1118_fu_481_p1 = esl_sext<31,16>(p_Val2_14_reg_850.read());
}

void Loop_realfft_be_desc::thread_sub_ln104_fu_265_p2() {
    sub_ln104_fu_265_p2 = (!ap_const_lv10_200.is_01() || !ap_phi_mux_i1_0_i_phi_fu_221_p4.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_200) - sc_biguint<10>(ap_phi_mux_i1_0_i_phi_fu_221_p4.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_1_fu_531_p2() {
    sub_ln1148_1_fu_531_p2 = (!ap_const_lv16_0.is_01() || !trunc_ln1148_1_reg_889.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(trunc_ln1148_1_reg_889.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_2_fu_515_p2() {
    sub_ln1148_2_fu_515_p2 = (!ap_const_lv18_0.is_01() || !zext_ln1148_1_fu_512_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_biguint<18>(zext_ln1148_1_fu_512_p1.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_3_fu_536_p2() {
    sub_ln1148_3_fu_536_p2 = (!ap_const_lv16_0.is_01() || !trunc_ln1148_4_reg_894.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(trunc_ln1148_4_reg_894.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_4_fu_431_p2() {
    sub_ln1148_4_fu_431_p2 = (!ap_const_lv16_0.is_01() || !trunc_ln1148_7_reg_815.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(trunc_ln1148_7_reg_815.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_5_fu_454_p2() {
    sub_ln1148_5_fu_454_p2 = (!ap_const_lv18_0.is_01() || !zext_ln1148_2_fu_415_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_biguint<18>(zext_ln1148_2_fu_415_p1.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_6_fu_470_p2() {
    sub_ln1148_6_fu_470_p2 = (!ap_const_lv16_0.is_01() || !trunc_ln1148_s_reg_845.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(trunc_ln1148_s_reg_845.read()));
}

void Loop_realfft_be_desc::thread_sub_ln1148_fu_496_p2() {
    sub_ln1148_fu_496_p2 = (!ap_const_lv18_0.is_01() || !zext_ln1148_fu_493_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_biguint<18>(zext_ln1148_fu_493_p1.read()));
}

void Loop_realfft_be_desc::thread_sub_ln703_fu_545_p2() {
    sub_ln703_fu_545_p2 = (!p_Val2_s_reg_779_pp0_iter8_reg.read().is_01() || !p_Val2_1_reg_785_pp0_iter8_reg.read().is_01())? sc_lv<16>(): (sc_bigint<16>(p_Val2_s_reg_779_pp0_iter8_reg.read()) - sc_bigint<16>(p_Val2_1_reg_785_pp0_iter8_reg.read()));
}

void Loop_realfft_be_desc::thread_tmp_4_fu_549_p3() {
    tmp_4_fu_549_p3 = ret_V_reg_791_pp0_iter9_reg.read().range(16, 16);
}

void Loop_realfft_be_desc::thread_tmp_5_fu_572_p3() {
    tmp_5_fu_572_p3 = ret_V_1_reg_803_pp0_iter9_reg.read().range(16, 16);
}

void Loop_realfft_be_desc::thread_tmp_6_fu_423_p3() {
    tmp_6_fu_423_p3 = r_V_fu_418_p2.read().range(16, 16);
}

void Loop_realfft_be_desc::thread_tmp_fu_300_p4() {
    tmp_fu_300_p4 = i1_0_i_reg_217_pp0_iter2_reg.read().range(9, 8);
}

void Loop_realfft_be_desc::thread_trunc_ln104_fu_271_p1() {
    trunc_ln104_fu_271_p1 = sub_ln104_fu_265_p2.read().range(8-1, 0);
}

void Loop_realfft_be_desc::thread_trunc_ln1148_2_fu_556_p4() {
    trunc_ln1148_2_fu_556_p4 = ret_V_reg_791_pp0_iter9_reg.read().range(16, 1);
}

void Loop_realfft_be_desc::thread_trunc_ln1148_5_fu_579_p4() {
    trunc_ln1148_5_fu_579_p4 = ret_V_1_reg_803_pp0_iter9_reg.read().range(16, 1);
}

void Loop_realfft_be_desc::thread_trunc_ln1148_8_fu_436_p4() {
    trunc_ln1148_8_fu_436_p4 = r_V_fu_418_p2.read().range(16, 1);
}

void Loop_realfft_be_desc::thread_trunc_ln99_fu_288_p1() {
    trunc_ln99_fu_288_p1 = i1_0_i_reg_217_pp0_iter1_reg.read().range(8-1, 0);
}

void Loop_realfft_be_desc::thread_twid_rom_0_address0() {
    twid_rom_0_address0 =  (sc_lv<9>) (zext_ln1265_fu_327_p1.read());
}

void Loop_realfft_be_desc::thread_twid_rom_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        twid_rom_0_ce0 = ap_const_logic_1;
    } else {
        twid_rom_0_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_twid_rom_1_address0() {
    twid_rom_1_address0 =  (sc_lv<9>) (zext_ln1265_fu_327_p1.read());
}

void Loop_realfft_be_desc::thread_twid_rom_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        twid_rom_1_ce0 = ap_const_logic_1;
    } else {
        twid_rom_1_ce0 = ap_const_logic_0;
    }
}

void Loop_realfft_be_desc::thread_zext_ln104_fu_283_p1() {
    zext_ln104_fu_283_p1 = esl_zext<64,8>(trunc_ln104_reg_671.read());
}

void Loop_realfft_be_desc::thread_zext_ln1148_1_fu_512_p1() {
    zext_ln1148_1_fu_512_p1 = esl_zext<18,17>(ret_V_1_reg_803_pp0_iter7_reg.read());
}

void Loop_realfft_be_desc::thread_zext_ln1148_2_fu_415_p1() {
    zext_ln1148_2_fu_415_p1 = esl_zext<18,17>(ret_V_3_reg_798.read());
}

void Loop_realfft_be_desc::thread_zext_ln1148_fu_493_p1() {
    zext_ln1148_fu_493_p1 = esl_zext<18,17>(ret_V_reg_791_pp0_iter7_reg.read());
}

void Loop_realfft_be_desc::thread_zext_ln1265_fu_327_p1() {
    zext_ln1265_fu_327_p1 = esl_zext<64,10>(i1_0_i_reg_217_pp0_iter3_reg.read());
}

void Loop_realfft_be_desc::thread_zext_ln99_fu_292_p1() {
    zext_ln99_fu_292_p1 = esl_zext<64,8>(trunc_ln99_fu_288_p1.read());
}

void Loop_realfft_be_desc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter12.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter11.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_fu_247_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter12.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter11.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln80_fu_247_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(regslice_both_dout_V_U_apdone_blk.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

